version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: rentify_django
    container_name: rentify_django
    command: /start.sh
    volumes:
      - .:/app
      - static-data:/vol/static
      - media-data:/vol/media
    ports:
      - 8000:8000
    env_file:
      - ./.env/.production/.django
    depends_on:
      - redis
      - db

  db:
    image: postgres:16-alpine
    container_name: rentify_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=rentify_hub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwertyuiopasdfghjklzxcvbnm

  redis:
    image: redis:7-alpine
    container_name: rentify_redis

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: rentify_celery_worker
    container_name: rentify_celery_worker
    command: /start-celeryworker.sh
    volumes:
      - .:/app
    env_file:
      - ./.env/.production/.celery
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: rentify_celery_beat
    container_name: rentify_celery_beat
    command: /start-celerybeat.sh
    volumes:
      - .:/app
    env_file:
      - ./.env/.production/.beat
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: rentify_celery_flower
    container_name: rentify_flower
    command: /start-flower.sh
    volumes:
      - .:/app
    env_file:
      - ./.env/.production/.flower
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db

  webpack:
    build:
      context: .
      dockerfile: ./compose/production/webpack/Dockerfile
    image: rentify_webpack
    container_name: rentify_webpack
    command: /start-webpack.sh
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development

  nginx:
    image: nginx:latest
    container_name: rentify_nginx
    ports:
      - 80:80  # Expose port 80 from the container to the host machine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Mount your custom Nginx configuration
      - static-data:/vol/static
      - media-data:/vol/media
    depends_on:
      - web  # Ensure Django is ready before Nginx starts

volumes:
  postgres_data:
  static-data:
  media-data:
